### ISSUE TITLE
Same route on the stack more than once

### ISSUE THREAD

**Issue by martinbooth** [LeoLeBras/react-router-navigation#30] opened 2017-08-01 06:45 UTC
https://github.com/LeoLeBras/react-router-navigation/blob/master/modules/DefaultRenderer.js#L54 seems to assume that routeName would be unique amongst all the scenes, but it doesn't have to be. In the event it's not unique, the wrong scene is rendered

**Comment by LeoLeBras** [comment] 2017-09-24 09:04
Hi @martinbooth Do you have an example that reproduces the issue?

**Comment by allenhsu** [comment] 2017-11-24 08:20
In my project, this is causing bugs in transition animation.

For example, there's a card for topic page:

```
<Card exact path='/topics/:topic_id' component={Topic} />
```

If you push a topic from a non-topic page, it's fine. But if you push a topic from another topic page, when the push begins, the first topic page will be rendered as the second one, and when popping, the first topic will remain as the second one until the second one unmount.

Because for the topic card, the route name is actually the path `/topics/:topic_id`, so the route name are same for both topic scenes. Then when searching for scene with route name, it always return the last matched one.

**Comment by allenhsu** [comment] 2017-11-24 08:33
But seems it's actually caused by how `react-navigation` looks for components, it only passes `routeName` to the `router`, I don't think it can be fixed in `react-router-navigation` unless reimplement the entire `CardStack`.

https://github.com/react-community/react-navigation/blob/master/src/views/CardStack/CardStack.js#L431

**Comment by allenhsu** [comment] 2017-11-24 09:53
I tried and double checked the code of `react-navigation`, this bug does not exist in `react-navigation`, because the default implementation is not caching scenes. Instead, it looks for the component, and wrap it into a SceneView which extends `PureComponent` then return. So different scenes with same routeName are always different components. Caching and optimization is done by PureComponent. Maybe we can do the same in `react-router-navigation`?

**Comment by LeoLeBras** [comment] 2018-10-01 20:43
This should be corrected with the recent changes made.

**Closed by LeoLeBras** 2018-10-01 20:43 UTC
Labels: needs more information 🤨, v1 stable 🔥
