### ISSUE TITLE
Property route undefined on replacement of route

### ISSUE THREAD

**Issue by georgberecz** [LeoLeBras/react-router-navigation#27] opened 2017-07-03 04:25 UTC
Hey Leo,
thanks for looking into https://github.com/LeoLeBras/react-router-navigation/issues/23 and updating the Renderer. The rendering of multiple cards is not a problem anymore. However, there is now an error inside the NavBar:
![image](https://user-images.githubusercontent.com/7314829/27777735-245eb770-5f7b-11e7-9d6b-1d70d51e8653.png)
![image](https://user-images.githubusercontent.com/7314829/27777823-e63c8d7c-5f7b-11e7-9ef4-9dcf50e0e260.png)

I'm using the newest release candidate:
`"react-router-navigation": "^1.0.0-rc.2",`

I looked into the code and I think I've found something. In the DefaultRenderer replacing 
`return [
  ...acc.slice(0,indexOf),
  scene
]`
with 
`return [...acc]`
and therefore, using the last occurrence in case of finding a duplicate index fixed it for me. With the old code the newly replaced route was simply sliced of again and replaced by the old one. However, the `scene` in the `ownProps` was still the new one, but could not be found in the newly generated `scenes`, which resulted in the exception.

Thanks for looking into that and keep up the good work,
Georg

**Comment by LeoLeBras** [comment] 2017-07-05 21:15
Hello @georgberecz ,
I can't reproduce your issue. You should consider creating a minimal test case to demonstrate the issue you're having 😀

**Comment by Vlad-Zhukov** [comment] 2017-07-24 12:16
Wasn't it fixed by #25?

**Comment by LeoLeBras** [comment] 2017-08-01 07:43
@georgberecz ?

**Comment by CharlesMangwa** [comment] 2017-08-02 21:10
Hi @georgberecz! Did you give a shot to the new ß3? Feel free to keep us update about your issue :)

**Comment by LeoLeBras** [comment] 2017-08-18 22:28
Closing due to inactivity

**Comment by insaneinc01** [comment] 2018-02-03 09:17
Thanks @georgberecz 

This actually worked 
`return [ ...acc.slice(0,indexOf), scene ]`
with
`return [...acc]`

I was getting the same error when using history.replace("...") the second time. It works the first time though.

**Comment by LeoLeBras** [comment] 2018-02-03 11:07
@insaneinc01 Do you have an example (or a Github) repo that reproduces the issue?

**Comment by LeoLeBras** [comment] 2018-03-15 23:03
This should be fixed in `1.0.0-rc.5`

**Closed by LeoLeBras** 2018-03-15 23:03 UTC
Labels: bug 🙃
